import '@/styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import { useCounter } from '@/hooks/useCounter'
import { useInputArray } from '@/hooks/useInputArray'
import { useBgLightBlue } from '@/hooks/useBgLightBlue'


export default function App({ Component, pageProps }: AppProps) {
  const counter = useCounter();
  const inputArray = useInputArray();
  useBgLightBlue();



  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} {...counter} {...inputArray} />
    </>
  )
}
