import Head from 'next/head'
import Main from './components/Main.js'
import Header from './components/Header.js'

export default function Home() {
  return (
    <>
      <Head>
        <title>index Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main page="index" />
    </>
  )
}
